### ISSUE TITLE
CSV export formatting issues from "Review and Edit Data"

### ISSUE THREAD

**Issue by robwwilliams** [genenetwork/genenetwork2#130]
The output of the CSV needs to be formatted correctly.
Try this trait for example 

http://gn2.genenetwork.org/show_trait?trait_id=12661&dataset=BXDPublish

,Index,Sample,Value,&nbsp;,SE
,97,BXD103,,Â±,
,96,BXD102,,Â±,
,95,BXD101,,Â±,
,94,BXD100,,Â±,
,93,BXD99,,Â±,
,92,BXD98,,Â±,
,91,BXD97,,Â±,
,90,BXD96,,Â±,
,89,BXD95,,Â±,
,88,BXD94,,Â±,
,87,BXD93,,Â±,
,86,BXD92,,Â±,
,85,BXD91,,Â±,
,84,

**Comment by zsloan** [comment]
Yeah, I'm aware of this. I looked into fixing it once before, but it's
actually pretty tricky to get the dataTables export button plugin to deal
with empty or strange input fields (for example, there's no value because
the value is inside of a text box). I think I'd have to either write some
dataTables extension or write my own javascript that grabs the data out of
the table for the export.

**Comment by pjotrp** [comment]
Is this because users can update the data? Why not use the data from the database otherwise?

**Comment by pjotrp** [comment]
If we have a ReST interface you'd be able to pull the data in JS.

**Comment by zsloan** [comment]
This is fixed now.
