### ISSUE TITLE
Download Table button not working in collections/view

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#141]
http://gn2.genenetwork.org/collections/view

**Comment by pjotrp** [comment]
Actually, the table view CSV downloads are not working on the live site (except for one). Also we have 'CSV' and 'Table Download' as buttons - settle on one or the other for consistency.

**Comment by zsloan** [comment]
I'm fixing this now. I figured out how to get around a couple issues with
the datatables Button feature and am adding it to all relevant tables. I
will remove the "Table Download" button for now, though in the future I
want to try linking the csv download to that custum button rather than the
default download button the extension creates.

**Comment by zsloan** [comment]
Closing this since it is fixed.
