### ISSUE TITLE
Index error in R/qtl

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#157]
When selecting this trait:

  http://test-gn2.genenetwork.org/show_trait?trait_id=1438373_at&dataset=HC_M2_0606_P

R/qtl throws an error in

marker_regression_gn1.py", line 2011, in drawQTL
    canvas.drawPolygon(LRSCoordXY,edgeColor=thisLRSColor,closed=0, edgeWidth=lrsEdgeWidth, clipX=(xLeftOffset, xLeftOffset + plotWidth))

**Comment by DannyArends** [comment]
This error occurs in the code for the plotting of the QTL graph.
I think the LRSCoordXY variable is empty

Is this dataset / trait in the small database, so that I can test it locally ?

**Comment by pjotrp** [comment]
The plot thickens.  The trait is in the small database.

The same search on the databases actually maps with R/qtl: http://localhost:5003/show_trait?trait_id=1438373_at&dataset=HC_M2_0606_P

The difference I see is that in the full database we now have a 'probes' button an SE is listed in the table.

**Comment by DannyArends** [comment]
Hmm if it maps with R/qtl then using the small database, then it might be unrelated to R/qtl and might be a bug in the QTL plotting code, I will try n reproduce the bug on my local install and see what happens.

**Comment by zsloan** [comment]
If it can do other mapping okay for the same trait, it seems unlikely to be
something directly related to the plotting code. It might be related to the
python code that processes the R/qtl results, though.

**Comment by zsloan** [comment]
This issue hasn't been updated in a while; do we know why only the small database threw this error?

One thing I forgot to mention in my previous comment is that LRSCoordXY should just = the results, so LRSCoordXY being empty should mean that no results were returned for whatever reason (causing the for loop to never run and LRSCoordXY to never be populated). 

So the issue is likely caused by the R/qtl mapping code needing something that isn't in the small database.

**Comment by zsloan** [comment]
I'm guessing this issue has been addressed? Been a couple years and there haven't been any issues with R/qtl.
