### ISSUE TITLE
When you call CTL with an empty collection we should display a message

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#195]
Currently the server bombs out with an empty collection

**Comment by pjotrp** [comment]
```
    list index out of range (error)
      File "/export2/izip/git/opensource/genenetwork/sumo_gn2/wqflask/wqflask/ctl/ctl_analysis.py", line 96, in run_analysis
        datasetname = self.trait_db_list[0].split(":")[1]
```

**Comment by pjotrp** [comment]
Easy to replicate on master http://test-gn2.genenetwork.org/. Create collection, but do not select any entries. Run CTL and you get above error. If you select one trait you get also an error. Two traits is fine, as it should be.

At least the user should get a nice response from the system, saying that you need at least 2 traits for CTL. Similar to what WGCNA does.

BTW @robwwilliams, maybe we should select the top five traits by default when you enter a collection?

**Comment by zsloan** [comment]
Actually GN1 automatically selects all traits if you don't select any
yourself. I should probably add that to GN2 as well.

I'll fix the CTL issue today. Is it better for me to intercept the user
when they click the CTL option and before they leave the page (and if so,
is there any way to do this without a pop-up, which we obviously don't
want)? Otherwise I could just make it return a page saying "Please select 2
or more traits."

**Comment by pjotrp** [comment]
@robwwilliams I prefer to show the use that he needs to select a number of traits. Too many traits and most tools will be slow. Let's select the first 3 automatically on page entry.

**Comment by pjotrp** [comment]
Thanks Zach for adding the error message. One problem left, in addition to above trait selection, is that one trait is missing Try and select 3 you get 2. Select 4 you get 3.

**Comment by zsloan** [comment]
That issue seems to just be because the template for some reason subtracted
1 from the length of trait_list; not sure why it did that, but removing the
"- 1" makes it display the correct number of traits. While checking this,
however, I noticed that I get an error when I try to run the analysis. The
error is for the line "*r_library("ctl")*" where it tries to load the ctl
library. Specifically, the error message is:

RRuntimeError: Error in (function (package, help, pos = 2, lib.loc = NULL,
> character.only = FALSE,  :
>   there is no package called 'ctl'


Do you have any idea why this might be? I didn't write any of the code for
CTL or WGCNA so I'm not sure why this might be happening (or when the error
first appeared, since I haven't had any need to work with CTL for a long
time).

**Comment by pjotrp** [comment]
CTl should work on the gn2-staging profile.

**Comment by zsloan** [comment]
Should I have pulled this fix? I pulled from testing branch and still have
error related to R importing the CTL package.

**Comment by pjotrp** [comment]
Fixed.
