### ISSUE TITLE
Collection should show informative message when too many items

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#196]
Currently, when selecting too many items, you get an uninformative message saying 'this content failed to load'. On 

http://test-gn2.genenetwork.org/search?species=mouse&group=BXD&type=Hippocampus+mRNA&dataset=HC_M2_0606_P&search_terms_or=%28chr1+25+30%29&search_terms_and=&FormID=searchResult

and do 'select all' followed by 'add'.

**Comment by zsloan** [comment]
This doesn't happen on production or my branch, so I think it's also
related to your test version. I'm guessing there's something causing
collections in general to not work correctly in that version.

There is a different issue that occurs if you try to create a very large
(several thousand traits) collection, but it occurs when you actually
create the collection (instead of when you just hit "add"). That issue
stems from limitation in the storeable collection size, though (rather than
something in the code).
