### ISSUE TITLE
Correlation Matrix: Or why I have not switch from GN1 to GN2 yet

### ISSUE THREAD

**Issue by robwwilliams** [genenetwork/genenetwork2#221]
1. Correlation plots lack full X axis and Y axis labels. GN1 provides full labels underneath the plots. GN2 has good labeling, but the labels do not include gene symbols, or full trait descriptions. Simple to fix.

2. No eigentraits computed from Correlation Matix. But at least GN2 has the factor loadings (Byron Jones will be happy)(.

3. No way to export the Correlation Matrix. GN1 has a few methods of doing this.

4. Font colors and sizes in the Correlation Matrix are an unattractive mix. Spacing is bad too. 

5. Should ask Karl, Saunak, and others for advice on best display etc for this page; what to show in the diagonal. Lots of cool stuff we could do:

Please do a Google "image" search for "Correlation Matrix". Here is one that is pretty cool

![screen shot 2016-11-01 at 11 39 44 am](https://cloud.githubusercontent.com/assets/12311292/19897905/f5df8a72-a027-11e6-93aa-a1735380688b.png)

https://www.google.com/imgres?imgurl=http://www.sthda.com/sthda/RDoc/figure/statistics/correlation-matrix-graph-1.png&imgrefurl=http://www.sthda.com/english/wiki/correlation-matrix-a-quick-start-guide-to-analyze-format-and-visualize-a-correlation-matrix-using-r-software&h=1152&w=1056&tbnid=8tNCCJc08yTVyM:&tbnh=160&tbnw=146&docid=T26z7tlylvyyDM&usg=__g47BfFc6qnxToULzlpjh4kL8VPQ=&sa=X&sqi=2&ved=0ahUKEwiAuLHj_ofQAhUBYCYKHfPGCC8Q9QEIIDAA

**Comment by zsloan** [comment]
While looking at this I noticed that for some bizarre reason a change I
made to add color to the cells (like in the example picture you attached)
was not being used. I'll add this back in in addition to the other stuff
you mentioned. As for each item:

1. By full labeling I assume you mean the face that GN1 shows the full
dataset name (whereas GN1 just shows the short one)? I can easily fix that.
Are you also referring to the Trait labels on the correlation matrix? If
you want me to also add the GN1 feature that lets you toggle between short
and long labels I can also do that.

2. This will be very tough, because it requires that we have a good way to
deal with temporary traits (which we don't currently). I don't think the
GN1 code can be directly ported, because it relies upon dealing with
temporary traits/datasets in the same way GN1 does. Probably the two
biggest and most important remaining projects for GN1 are 1. dealing with
temporary traits (like the eigentraits or user-inputted traits) and 2.
authentication/security stuff. This will be a pretty big project.

3. I can add this and make it like the GN1 export.

4. I'll try to improve this. I can try to make the font/spacing like in the
attached image (though the font size will have to be smaller to fit the N).

5. I'm fine with this, though we might need to use some other graphing
library if you want to do something like add an image in the diagonal
cells. If I recall correctly, the main issue I ran into while looking for
correlation matrix graphing libraries is that they usually don't show both
pearson and spearman on each half of the figure and also sometimes have the
diagonal flipped.

**Comment by robwwilliams** [comment]
Zach:  Yes, in GN2 under the individual X-Y plots we provide more information on the traits on the X and Y axis. It would be great to show that much information or even more. Could be a "show-hide" switch.

One the Correlation Matrix: yes, it would be great to have the three levels of verbosity that GN1 uses. 

2. Hmm, let's talk about this with Pjotr and Lei. One of the great features of GN1 are these synthetic traits. It would be good to do even better than GN1. 

3 and 4. Our Correlation Matrix is a bit cluttered with the N and the r or rho value. Could make this switchable and keep it simple for the default (just the r). Export is important, including an export of a proper factor analysis (?). 

5. Karl has done some of this. Check out his D3 code. He will be here tomorrow and we can get his advice.
