### ISSUE TITLE
Option for flushing gemma cache

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#283]
We need a checkbox in the mapping page to flush the gemma cache so a computation gets forced again. We should also flush cache when we restart the server. @zsloan we should not share the file storage with your development tree. GENENETWORK_FILES should point into a non-mutable space.

See also #282

**Comment by zsloan** [comment]
Where would be a good place to put the files (like, which directory from
the base directory)? I'm not sure where it's "normal" to put files like
this.

**Comment by pjotrp** [comment]
Intermediate files should go in TMPDIR and related.

Fixed genotype files should be in GENENETWORK_FILES and related.

Anything mutable should not go in the latter.

We'll soon start using IPFS. GENENETWORK_FILES will point into that. Nothing can mutate.

**Comment by zsloan** [comment]
How should this be done? I'd think it would be some sort of option in GEMMA wrapper itself, since I think that's where it checks to see if results are cached. While the directory with the cached files could be emptied, that seems like a bad idea since we don't want a user to be able to remove the cache for other users.
