### ISSUE TITLE
pylmm fails

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#326]
Using http://gn2.genenetwork.org/show_trait?trait_id=1433387_at&dataset=HC_M2_0606_P

Something with redis?

```
    GeneNetwork penguin:gene:2.11-rc2-production-0bead5366 http://gn2.genenetwork.org/marker_regression (10:13AM UTC Jun 13, 2018)
    ERROR: failed on /usr/local/guix-profiles/gn2-latest/bin/pylmm_redis --key pylmm:input:66aa51c7-f136-41db-9794-3c743cff2123 --species other (error)
      File "/home/production/gene/wqflask/utility/external.py", line 9, in shell
        raise Exception("ERROR: failed on "+command)
```

**Comment by zsloan** [comment]
This seems to just mean that an error is occurring within the external
module (which is called pylmm_redis but just runs all the pylmm code). I
can take a look at it later (though I'm not sure how best to debug it other
than printing to a debug file), but it might take a while since I have
little familiarity with the actual internal pylmm code. In the meanwhile
I'll just remove the option so no one hits the error (it's kind of
redundant anyways as long as GEMMA is there).

**Comment by pjotrp** [comment]
It gets the data from redis - looks like a species problem.

**Comment by pjotrp** [comment]
Since we are no longer using pylmm
