### ISSUE TITLE
QTL mapping issues: QTLs have changed location

### ISSUE THREAD

**Issue by squirrelB** [genenetwork/genenetwork2#402]
Hi all. Beni here. Took a little break from GN for a few weeks, and now I'm back! Apologies that I'm already sending "issues"! 
Unfortunately,  I've run into a couple of problem with the BXD NIA Longevity group.

1) QTL mapping function is not working for temporary traits that are submitted from the trait submission page. It seems to work fine for traits that are already in GN2.

2) And here's the part that almost sent me into a bit of a crisis... the GEMMA QTL maps look completely changed. The map I got from back in April/May 2020 looks different than now, for the same trait (for example BDL_10019). I think what's happening is it's simply a graphing issue and the loci are getting shifted by about a chromosome. What used to be on Chr 11 is now on chr 12. The Haley-Knott looks the same, so it's just specific to GEMMA.

3) Not an issue but a suggestion. In the GEMMA plot, the markers are colored red and blue, which I think is the additive effect. I couldn't see a legend explain the color codes (blue I think is D allele high). Maybe helpful to have that.

Thanks

**Comment by zsloan** [comment]
Ahh, the red/blue thing is unrelated to additive effect. They're supposed
to be alternating by chromosome just for aesthetic reasons, but there's
some issue with that group (I think it's just that group) that is making
them alternate for every marker instead of by chromosome. It might be the
same as whatever issue is making the mapping results different; I'll take a
look and see if I can figure out what might be going wrong.

The temporary trait thing is a known issue; it should be fixed pretty soon
(probably within the next week).

**Comment by zsloan** [comment]
Oh, I see what's going on. The positions are all messed up (the red/blue
are overlapping because it starts drawing each chromosome in the wrong
place). This is likely the reason for both the difference in mapping
results and the red/blue issue. I'll try to fix this tomorrow.

**Comment by zsloan** [comment]
It's fixed on my branch now (I'll try to move the changes to production
tomorrow, but you can run it on my branch for now).

For example
http://gn2-zach.genenetwork.org/show_trait?trait_id=10005&dataset=BXD-HarvestedPublish

The issue was related to the option for selecting mapping scale that was
added a while back (it was wrongly thinking that it was supposed to the
centimorgans, causing the marker positions to end up all wrong).
