### ISSUE TITLE
[Bug] Error message on gn2 proxy

### ISSUE THREAD

**Issue by BonfaceKilz** [genenetwork/genenetwork2#440]
**Describe the bug**

On the Python3 branch, I'm getting:

```
/run-action?resource=d5e4c7434c9995c83e0e&user=9ea7c628-87aa-4619-aa13-29c347995537&branch=data&action=view&trait=1435395_s_at ~~> string=?: contract violation
    expected: string?
    given: '("no-access" "view")
    argument position: 2nd
    other arguments...:
     "no-access"
  /available?resource=d5e4c7434c9995c83e0e&user=9ea7c628-87aa-4619-aa13-29c347995537 ~~> string=?: contract p
```

**To Reproduce**

- Switch to the python3 branch: https://github.com/genenetwork/genenetwork2/pull/422
- Run the proxy
- Launch GN2
- Search for any query

**Expected behavior**

Nothing should be displayed from the gn2 proxy

**Screenshots**

N/A

**Environment setup (please complete the following information):**

- OS: ArchLinux with Guix as the primary Package Manager

**Additional context**

N/A

**Comment by BonfaceKilz** [comment]
Also, on Penguin2 I was getting:

```
  ERROR:wqflask.views:.handle_bad_request: 17:37:32 UTC 20200831: (_mysql_exceptions.ProgrammingError) (1146, "Table 'db_webqtl_s.RatSnpPattern' doesn't exist")
  [SQL: SHOW COLUMNS FROM RatSnpPattern;]
  (Background on this error at: http://sqlalche.me/e/13/f405)
  ERROR:wqflask.views:.handle_bad_request: 17:37:32 UTC 20200831: http://localhost:5004/snp_browser?first_run=true&species0
```

I'm guessing that's a very recent table(?)

**Comment by zsloan** [comment]
Ah, that table (RatSnpPattern) was added semi-recently (like within the
last year or two, which was after the small DB was created). That table's
existence is actually a good example of the sort of issue Pjotr mentioned
(in this case we had a "SnpPattern" table that assumed there would only be
mice data, and ended up having to make a separate one, since adding a new
column to SnpPattern would have broken a lot of things).

**Comment by BonfaceKilz** [comment]
This is probably the issue: https://github.com/genenetwork/genenetwork2/pull/422/commits/46443ec8d2cdfd7c60358a889d90a90e4f7daaf4. Note the difference in Python2 and Python3: https://stackoverflow.com/questions/31848293/python3-and-hmac-how-to-handle-string-not-being-binary. I'll look in to that more deeply later today.

**Comment by BonfaceKilz** [comment]
I've been able to narrow down the problem. In webqtlConfig.py, we have:

```
SUPER_PRIVILEGES = {'data': ['no-access', 'view', 'edit'], 'metadata': ['no-access', 'view', 'edit'], 'admin': ['not-admin', 'edit-access', 'edit-admins']}
DEFAULT_PRIVILEGES = {'data': ['no-access', 'view'], 'metadata': ['no-access', 'view'], 'admin': ['not-admin']}
```

I've had a look at the proxy code, and I'm guessing that those should be set to only one value. Something like:

```diff
- SUPER_PRIVILEGES = {'data': ['no-access', 'view', 'edit'], 'metadata': ['no-access', 'view', 'edit'], 'admin': ['not-admin', 'edit-access', 'edit-admins']}
+ SUPER_PRIVILEGES = {'data':  'edit', 'metadata': 'edit', 'admin': 'edit-admins'}
- DEFAULT_PRIVILEGES = {'data': ['no-access', 'view'], 'metadata': ['no-access', 'view'], 'admin': ['not-admin']}
+ DEFAULT_PRIVILEGES = {'data': 'view', 'metadata': 'view', 'admin': 'not-admin'}
```

@zsloan or @chfi is that correct?

**Comment by zsloan** [comment]
I'm pretty sure it should be changed like you mentioned, yeah. My guess is
that this issue didn't show up yet on production or my branch because most
resources had their defaults set already (and that script sets them like
you mention). I'm guessing this issue is probably occurring when it sets
the resource's default privileges and then the proxy encounters that.

**Comment by BonfaceKilz** [comment]
Going ahead to close this since we can explain the above error message.
