### ISSUE TITLE
Basic statistics for datasets with case attributes are not shown properly

### ISSUE THREAD

**Issue by lomereiter** [genenetwork/genenetwork2#48]
E.g. http://gn2.genenetwork.org/show_trait?trait_id=210749_x_at&dataset=GSE5281_F_RMA0709 - no stats, histogram and bar chart.

**Comment by lomereiter** [comment]
Fixed in my `issue28` branch, will make a PR after fixing more bugs in bar chart code.

**Comment by robwwilliams** [comment]
Lei, Zach, Artem,

We need to clean up number formats in these and all other tables. Here are some minor problems that need to be handled:

1. "Additive Effect" is given with 12 digits of precision, but 3 digits are adequate.  

2. Location (Chr and Mb). The Mb values should all be given with 6 digits of precision to avoid ambiguity. For example, the value 34.2721 should read 34.272100 Mb.  Most genomics web sites use bp and would list this as 34272100, but I find this format quite hard to read. Megabase format is for humans; bp for machines.

3. There is also no index number field on the far left. We must have an index number in all tables so that export and screen scrapes know if they got everything or dropped lines.

4. Need to tweak the column spacing for the Max LRS column. The LRS values are out of alignment with the column.  Symbol column also seems misaligned by a few pixels.

5. Mean and Max LRS numbers should be justified to the right. Max LRS is done correctly (but see note above), but Mean is justified to the left and looks goofy.
