### ISSUE TITLE
Sex/extra attribute column blank for C57BL-6JxC57BL-6NJF2 data set

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#64]
I think that this might be related to there being multiple ways of coding male/female in the database for the "Sex" case attribute ("M","m","male", etc).

**Comment by lomereiter** [comment]
This is not the case, the values are only 'M' and 'F'.

The extra attribute values are not fetched from the database because this dataset is of type 'Publish' and not 'ProbeSet': 
https://github.com/genenetwork/genenetwork2/blob/b3058f8c3710c65288d88ed777aa0fcad8429aef/wqflask/wqflask/show_trait/SampleList.py#L58-L60
Removing the type restriction in that `if` makes everything work, BUT I don't understand then what is the purpose of `ProbeSetFreezeId` column in `CaseAttributeXRef` table.
