### ISSUE TITLE
Bug: Select download PDF breaks for single chromosome

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#80]
After interval mapping, when I select one chromosome view of the QTL map the PDF download fails with an Internal Server Error. PDF does work for the full map so it is probably something minor (SVG may be working).

**Comment by mamarjan** [comment]
Same issue, but on both the whole genome and per-chromosome view. For PDF I get "Internal Server Error" too, but for SVG the export "succeeds", but I see firefox downloaded a file 0 bytes in size.

I'm on Firefox on Ubuntu 14.04.

**Comment by lomereiter** [comment]
For PDF exporting, I had to install `libffi-dev` package and `cairosvg` python module. It still doesn't work, though, as the converted SVG is an empty string, leading to SVG parsing error. So with the module installed, the problem is reduced to that of empty SVG, as there should be no issues inside the `cairosvg.svg2pdf` function.
