### ISSUE TITLE
Mb column for Barley species

### ISSUE THREAD

**Issue by lomereiter** [genenetwork/genenetwork2#87]
The numbers seem to be off by several orders of magnitude (6?)

```
 select avg(Mb) from Geno where SpeciesId = 5;
+------------------+
| avg(Mb)          |
+------------------+
| 51160355.7522124 |
+------------------+
1 row in set (0.12 sec)
```

**Comment by zsloan** [comment]
It appears that the bases instead of megabases were input for this species (thus the 6 magnitude difference). 

Unless there's some reason for this that I'm not aware of, it looks like we should just have Lei divide all those values by 10^6 in the database.

**Comment by robwwilliams** [comment]
Artem: not quite sure of the context, but megabase versus basepair is a 6
order difference. Many sites use basepair coordinates, but we convert to
Megabases since they are much easier for humans to read and round.

On Tue, Jul 7, 2015 at 10:33 AM, Artem Tarasov <notifications@github.com>
wrote:

> The numbers seem to be off by several orders of magnitude (6?)
>
>  select avg(Mb) from Geno where SpeciesId = 5;
> +------------------+
> | avg(Mb)          |
> +------------------+
> | 51160355.7522124 |
> +------------------+
> 1 row in set (0.12 sec)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/genenetwork/genenetwork2/issues/87>.
>



-- 
Rob

Robert W. Williams, Ph.D.
UT-ORNL Governor's Chair in Computational Genomics
Chair, Department of Genetics, Genomics and Informatics
University of Tennessee Health Science Center
Room 501
855 Monroe Avenue, Memphis TN 38163 USA

Office 901 448-7018  CELL 901
Office: 501 Wittenborg Building
EMAIL: rwilliams@uthsc.edu
Alternative email: labwilliams@gmail.com
SKYPE: robwwilliams

**Comment by zsloan** [comment]
Rob, since the Barley genotype Mb values all seem to be in bases instead of Megabases, should we go ahead and multiply them all by a million in the database?

**Comment by robwwilliams** [comment]
Sure, but we need some place in GN2 to store metadata on units and scales
of data sets. In this case "divide by".

On Wednesday, July 8, 2015, zsloan <notifications@github.com> wrote:

> Rob, since the Barley genotype Mb values all seem to be in bases instead
> of Megabases, should we go ahead and multiply them all by a million in the
> database?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/genenetwork/genenetwork2/issues/87#issuecomment-119629893>
> .
>


-- 
Rob

Robert W. Williams, Ph.D.
UT-ORNL Governor's Chair in Computational Genomics
Chair, Department of Genetics, Genomics and Informatics
University of Tennessee Health Science Center
Room 501
855 Monroe Avenue, Memphis TN 38163 USA

Office 901 448-7018  CELL 901
Office: 501 Wittenborg Building
EMAIL: rwilliams@uthsc.edu
Alternative email: labwilliams@gmail.com
SKYPE: robwwilliams
