### ISSUE TITLE
Sorting search results by 'Year' column works incorrectly

### ISSUE THREAD

**Issue by lomereiter** [genenetwork/genenetwork2#88]
Because each cell contains HTML that starts with `<a href>` to the PubMed entry, the results are in effect sorted by PubMed_ID instead of year. This needs use of custom sorting function such as done [here](https://github.com/genenetwork/genenetwork2/blob/e5cd03134e1f1ea39b9703c37e789ddc22f5b8c6/wqflask/wqflask/templates/search_result_page.html#L125-L160).

**Comment by lomereiter** [comment]
OK, it seems we can just update DataTables to 1.10+, and then everything is going to just work, it even detects numeric columns automatically, without an explicit request.

**Comment by robwwilliams** [comment]
Sorting of all columns should always move N/A and UN and empty fields to the end. In the Max LRS column, N/A sorts to the top.

**Comment by zsloan** [comment]
I tried locally installing the latest version of DataTables (1.10.12) and for some reason this caused one of the extensions to not work (with an error message say "this is only supported on version 1.10 or above"). Referring to the CDN url for the exact same version fixes this issue. I know we want to only refer to local files, but I don't know what is causing this.

Regardless, neither seems to fix the year sorting issue by default. I was able to fix it by just adding a "data-sort" attribute to the table cell telling it to only sort by the year itself, so I guess I'll close this issue since it no longer exists (though the issue regarding storing all JS/CSS locally still remains).
